"""Build reproducible verification metrics and figures for the TFM.

The script consumes the strict V2/Cantera campaigns generated by the two FGM
drivers.  It never solves a flame: it only aligns accepted profiles, evaluates
conservation diagnostics, performs leave-one-out interpolation in mixture
fraction, and writes the compact evidence used by the thesis.
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

import numpy as np


PHI_VALUES = (0.7, 0.9, 1.0, 1.1, 1.4)
MESH_LEVELS = ("coarse", "base", "strict", "ultra")
PROFILE_SPECIES = ("CH4", "O2", "CO2", "H2O", "CO", "OH")
V2_RUN = "v2_strict_final"
CANTERA_RUN = "cantera_strict_direct"
UNBOUNDED_RUN = "v2_unbounded_final"


def _phi_tag(phi: float) -> str:
    return f"phi_{phi:.6f}".replace(".", "p") + ".npz"


def _load_npz(path: Path) -> dict[str, np.ndarray]:
    with np.load(path, allow_pickle=True) as data:
        return {name: data[name] for name in data.files}


def _load_profile(root: Path, solver: str, phi: float) -> dict[str, np.ndarray]:
    return _load_npz(root / solver / "raw_profiles" / _phi_tag(phi))


def _thermal_origin(profile: dict[str, np.ndarray]) -> float:
    z = np.asarray(profile["z"], dtype=float)
    temperature = np.asarray(profile["T"], dtype=float)
    target = float(temperature[0] + 0.5 * (temperature[-1] - temperature[0]))
    candidates = np.flatnonzero(temperature >= target)
    if not candidates.size or int(candidates[0]) == 0:
        return float(z[np.argmin(np.abs(temperature - target))])
    j = int(candidates[0])
    return float(np.interp(target, temperature[j - 1 : j + 1], z[j - 1 : j + 1]))


def _aligned_grid(
    v2: dict[str, np.ndarray], cantera: dict[str, np.ndarray], points: int = 4001
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    z_v2 = np.asarray(v2["z"], dtype=float) - _thermal_origin(v2)
    z_ct = np.asarray(cantera["z"], dtype=float) - _thermal_origin(cantera)
    lower = max(float(z_v2[0]), float(z_ct[0]))
    upper = min(float(z_v2[-1]), float(z_ct[-1]))
    return np.linspace(lower, upper, points), z_v2, z_ct


def _interp(values: np.ndarray, source_z: np.ndarray, target_z: np.ndarray) -> np.ndarray:
    values = np.asarray(values, dtype=float)
    if values.ndim == 1:
        return np.interp(target_z, source_z, values)
    return np.vstack([np.interp(target_z, source_z, row) for row in values])


def _relative_l2(values: np.ndarray, reference: np.ndarray) -> float:
    return float(
        np.linalg.norm(values - reference)
        / (np.linalg.norm(reference) + np.finfo(float).tiny)
    )


def _edge_slopes(profile: dict[str, np.ndarray]) -> tuple[float, float]:
    z = np.asarray(profile["z"], dtype=float)
    temperature = np.asarray(profile["T"], dtype=float)
    reference = (temperature[-1] - temperature[0]) / (z[-1] - z[0])
    left = abs((temperature[1] - temperature[0]) / (z[1] - z[0]) / reference)
    right = abs((temperature[-3] - temperature[-1]) / (z[-3] - z[-1]) / reference)
    return float(left), float(right)


def _profile_metrics(root: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for phi in PHI_VALUES:
        v2 = _load_profile(root, V2_RUN, phi)
        cantera = _load_profile(root, CANTERA_RUN, phi)
        common_z, z_v2, z_ct = _aligned_grid(v2, cantera)

        temperature_v2 = _interp(v2["T"], z_v2, common_z)
        temperature_ct = _interp(cantera["T"], z_ct, common_z)
        qdot_v2 = _interp(v2["qdot"], z_v2, common_z)
        qdot_ct = _interp(cantera["qdot"], z_ct, common_z)
        species_v2 = _interp(v2["Y"], z_v2, common_z)
        species_ct = _interp(cantera["Y"], z_ct, common_z)

        names = [str(name) for name in cantera["species_names"].tolist()]
        index = {name: i for i, name in enumerate(names)}
        mass_flux_v2 = np.asarray(v2["rho"] * v2["u"], dtype=float)
        mass_flux_ct = np.asarray(cantera["rho"] * cantera["u"], dtype=float)

        record: dict[str, Any] = {
            "phi": phi,
            "Su_v2": float(v2["u"][0]),
            "Su_cantera": float(cantera["u"][0]),
            "Su_error_percent": 100.0
            * abs(float(v2["u"][0] - cantera["u"][0]))
            / abs(float(cantera["u"][0])),
            "nodes_v2": int(v2["z"].size),
            "nodes_cantera": int(cantera["z"].size),
            "width_v2_m": float(v2["z"][-1] - v2["z"][0]),
            "width_cantera_m": float(cantera["z"][-1] - cantera["z"][0]),
            "mass_flow_error_v2": float(
                np.max(np.abs(mass_flux_v2 - np.mean(mass_flux_v2)))
                / (abs(np.mean(mass_flux_v2)) + np.finfo(float).tiny)
            ),
            "mass_flow_error_cantera": float(
                np.max(np.abs(mass_flux_ct - np.mean(mass_flux_ct)))
                / (abs(np.mean(mass_flux_ct)) + np.finfo(float).tiny)
            ),
            "mass_fraction_sum_error_v2": float(
                np.max(np.abs(np.sum(v2["Y"], axis=0) - 1.0))
            ),
            "mass_fraction_sum_error_cantera": float(
                np.max(np.abs(np.sum(cantera["Y"], axis=0) - 1.0))
            ),
            "edge_slope_left_v2": _edge_slopes(v2)[0],
            "edge_slope_right_v2": _edge_slopes(v2)[1],
            "edge_slope_left_cantera": _edge_slopes(cantera)[0],
            "edge_slope_right_cantera": _edge_slopes(cantera)[1],
            "burned_temperature_v2_K": float(v2["T"][-1]),
            "burned_temperature_cantera_K": float(cantera["T"][-1]),
            "temperature_l2_dynamic": float(
                np.linalg.norm(temperature_v2 - temperature_ct)
                / (
                    np.linalg.norm(temperature_ct - temperature_ct[0])
                    + np.finfo(float).tiny
                )
            ),
            "temperature_linf_K": float(
                np.max(np.abs(temperature_v2 - temperature_ct))
            ),
            "qdot_l2_relative": _relative_l2(qdot_v2, qdot_ct),
            "qdot_linf_relative": float(
                np.max(np.abs(qdot_v2 - qdot_ct))
                / (np.max(np.abs(qdot_ct)) + np.finfo(float).tiny)
            ),
            "species": {},
        }
        for species in PROFILE_SPECIES:
            k = index[species]
            record["species"][species] = {
                "l2_relative": _relative_l2(species_v2[k], species_ct[k]),
                "linf_absolute": float(np.max(np.abs(species_v2[k] - species_ct[k]))),
            }
        records.append(record)
    return records


def _read_summary(path: Path) -> dict[str, str]:
    with path.open(newline="", encoding="utf-8") as stream:
        return next(csv.DictReader(stream))


def _mesh_metrics(root: Path) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    mesh_root = root / "mesh_study"
    for level in MESH_LEVELS:
        for solver in ("v2", "cantera"):
            row = _read_summary(mesh_root / f"{solver}_{level}" / "summary_phi.csv")
            output.append(
                {
                    "solver": solver,
                    "level": level,
                    "Su_m_per_s": float(row["Su_m_per_s"]),
                    "nodes": int(row["n_points"]),
                    "width_m": float(row["width_m"]),
                    "solve_time_s": float(row["solve_time_s"]),
                }
            )
    for solver in ("v2", "cantera"):
        rows = [row for row in output if row["solver"] == solver]
        reference = rows[-1]["Su_m_per_s"]
        for row in rows:
            row["Su_change_to_ultra_percent"] = (
                100.0 * abs(row["Su_m_per_s"] - reference) / abs(reference)
            )
    return output


def _table_validation(root: Path) -> dict[str, Any]:
    output: dict[str, Any] = {}
    for solver in (V2_RUN, CANTERA_RUN):
        table = _load_npz(root / solver / "fgm_table.npz")
        z_grid = np.asarray(table["Z_grid"], dtype=float)
        species = np.asarray(table["Y"], dtype=float)
        leave_one_out: list[dict[str, float]] = []
        for i in range(1, z_grid.size - 1):
            weight = (z_grid[i] - z_grid[i - 1]) / (z_grid[i + 1] - z_grid[i - 1])
            predicted_temperature = (
                (1.0 - weight) * table["T"][i - 1] + weight * table["T"][i + 1]
            )
            predicted_qdot = (
                (1.0 - weight) * table["qdot"][i - 1]
                + weight * table["qdot"][i + 1]
            )
            predicted_omega_c = (
                (1.0 - weight) * table["omega_c"][i - 1]
                + weight * table["omega_c"][i + 1]
            )
            predicted_species = (
                (1.0 - weight) * species[i - 1] + weight * species[i + 1]
            )
            temperature_reference = table["T"][i]
            leave_one_out.append(
                {
                    "phi": float(table["phi_grid"][i]),
                    "temperature_l2_dynamic": float(
                        np.linalg.norm(predicted_temperature - temperature_reference)
                        / (
                            np.linalg.norm(
                                temperature_reference - temperature_reference[0]
                            )
                            + np.finfo(float).tiny
                        )
                    ),
                    "temperature_linf_K": float(
                        np.max(np.abs(predicted_temperature - temperature_reference))
                    ),
                    "qdot_l2_relative": _relative_l2(
                        predicted_qdot, table["qdot"][i]
                    ),
                    "omega_c_l2_relative": _relative_l2(
                        predicted_omega_c, table["omega_c"][i]
                    ),
                    "species_linf_absolute": float(
                        np.max(np.abs(predicted_species - species[i]))
                    ),
                }
            )
        output[solver] = {
            "n_c": int(table["c_grid"].size),
            "mass_fraction_sum_error": float(
                np.max(np.abs(np.sum(species, axis=1) - 1.0))
            ),
            "leave_one_out": leave_one_out,
        }
    return output


def _continuation_ablation(root: Path) -> dict[str, Any]:
    variants = {
        "bounded": root / V2_RUN / "summary_phi.csv",
        "unbounded": root / UNBOUNDED_RUN / "summary_phi.csv",
    }
    output: dict[str, Any] = {}
    for name, path in variants.items():
        with path.open(newline="", encoding="utf-8") as stream:
            rows = [dict(row) for row in csv.DictReader(stream)]
        output[name] = {
            "solve_time_s": [float(row["solve_time_s"]) for row in rows],
            "nodes": [int(row["n_points"]) for row in rows],
            "Su": [float(row["Su_m_per_s"]) for row in rows],
            "total_solve_time_s": float(sum(float(row["solve_time_s"]) for row in rows)),
        }
    bounded = output["bounded"]["total_solve_time_s"]
    unbounded = output["unbounded"]["total_solve_time_s"]
    output["speedup"] = float(unbounded / bounded)
    output["time_reduction_percent"] = float(100.0 * (unbounded - bounded) / unbounded)
    return output


def _batch_comparison(root: Path) -> dict[str, Any]:
    """Summarize the matched strict cold sweeps without mixing timing scopes."""
    data: dict[str, Any] = {}
    for label, run in (("v2", V2_RUN), ("cantera", CANTERA_RUN)):
        path = root / run / "summary_phi.csv"
        with path.open(newline="", encoding="utf-8") as stream:
            rows = [dict(row) for row in csv.DictReader(stream)]
        data[label] = {
            "solve_time_s": [float(row["solve_time_s"]) for row in rows],
            "nodes": [int(row["n_points"]) for row in rows],
            "Su": [float(row["Su_m_per_s"]) for row in rows],
            "total_solve_time_s": float(
                sum(float(row["solve_time_s"]) for row in rows)
            ),
        }
    data["solve_speedup"] = float(
        data["cantera"]["total_solve_time_s"]
        / data["v2"]["total_solve_time_s"]
    )
    data["max_Su_error_percent"] = float(
        100.0
        * np.max(
            np.abs(np.asarray(data["v2"]["Su"]) - np.asarray(data["cantera"]["Su"]))
            / np.abs(np.asarray(data["cantera"]["Su"]))
        )
    )
    return data


def _write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row[field] for field in fields})


def _make_figures(
    root: Path,
    figure_dir: Path,
    profiles: list[dict[str, Any]],
    mesh: list[dict[str, Any]],
    table_validation: dict[str, Any],
    continuation: dict[str, Any],
) -> None:
    import matplotlib.pyplot as plt

    figure_dir.mkdir(parents=True, exist_ok=True)
    plt.rcParams.update(
        {
            "font.size": 9,
            "axes.labelsize": 9,
            "legend.fontsize": 8,
            "figure.dpi": 160,
            "savefig.bbox": "tight",
        }
    )

    v2 = _load_profile(root, V2_RUN, 1.0)
    cantera = _load_profile(root, CANTERA_RUN, 1.0)
    common_z, z_v2, z_ct = _aligned_grid(v2, cantera)
    fig, axes = plt.subplots(2, 1, figsize=(6.5, 5.6), sharex=True)
    axes[0].plot(1e3 * z_ct, cantera["T"], label="Cantera", color="#d97706")
    axes[0].plot(1e3 * z_v2, v2["T"], "--", label="V2", color="#155c8a")
    axes[0].set_ylabel("Temperatura [K]")
    axes[0].legend()
    axes[1].plot(1e3 * z_ct, cantera["qdot"] / 1e9, color="#d97706")
    axes[1].plot(1e3 * z_v2, v2["qdot"] / 1e9, "--", color="#155c8a")
    axes[1].set_ylabel(r"$\dot q$ [$10^9$ W m$^{-3}$]")
    axes[1].set_xlabel(r"Coordenada alineada $z-z_{T_{50}}$ [mm]")
    for axis in axes:
        axis.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(figure_dir / "perfil_estricto_phi1.pdf")
    plt.close(fig)

    fig, axis = plt.subplots(figsize=(6.5, 3.8))
    for solver, color, marker, label, annotation_offset in (
        ("v2", "#155c8a", "o", "V2", (4, -11)),
        ("cantera", "#d97706", "s", "Cantera", (4, 5)),
    ):
        rows = [row for row in mesh if row["solver"] == solver]
        axis.plot(
            [row["nodes"] for row in rows],
            [row["Su_m_per_s"] for row in rows],
            marker=marker,
            color=color,
            label=label,
        )
        for row in rows:
            axis.annotate(
                row["level"],
                (row["nodes"], row["Su_m_per_s"]),
                xytext=annotation_offset,
                textcoords="offset points",
                fontsize=7,
            )
    axis.set_xlabel("Número de nodos")
    axis.set_ylabel(r"$S_u$ [m/s]")
    axis.grid(alpha=0.25)
    axis.legend()
    fig.tight_layout()
    fig.savefig(figure_dir / "convergencia_malla_phi1.pdf")
    plt.close(fig)

    fig, axes = plt.subplots(1, 2, figsize=(7.0, 3.4))
    phi = [row["phi"] for row in profiles]
    axes[0].semilogy(
        phi,
        [row["mass_flow_error_v2"] for row in profiles],
        "o-",
        color="#155c8a",
        label="V2",
    )
    axes[0].semilogy(
        phi,
        [row["mass_flow_error_cantera"] for row in profiles],
        "s--",
        color="#d97706",
        label="Cantera",
    )
    axes[0].set_ylabel(r"$E_m$")
    axes[0].set_xlabel(r"$\phi$")
    axes[0].legend()
    axes[1].semilogy(
        phi,
        [row["mass_fraction_sum_error_v2"] for row in profiles],
        "o-",
        color="#155c8a",
    )
    axes[1].semilogy(
        phi,
        [row["mass_fraction_sum_error_cantera"] for row in profiles],
        "s--",
        color="#d97706",
    )
    axes[1].set_ylabel(r"$E_Y$")
    axes[1].set_xlabel(r"$\phi$")
    for axis in axes:
        axis.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(figure_dir / "conservacion_barrido.pdf")
    plt.close(fig)

    fig, axes = plt.subplots(1, 2, figsize=(7.0, 3.4))
    for solver, color, marker, label in (
        (V2_RUN, "#155c8a", "o", "V2"),
        (CANTERA_RUN, "#d97706", "s", "Cantera"),
    ):
        rows = table_validation[solver]["leave_one_out"]
        phis = [row["phi"] for row in rows]
        axes[0].plot(
            phis,
            [100.0 * row["temperature_l2_dynamic"] for row in rows],
            marker=marker,
            color=color,
            label=label,
        )
        axes[1].plot(
            phis,
            [100.0 * row["qdot_l2_relative"] for row in rows],
            marker=marker,
            color=color,
            label=label,
        )
    axes[0].set_ylabel("Error L2 de temperatura [%]")
    axes[1].set_ylabel(r"Error L2 de $\dot q$ [%]")
    for axis in axes:
        axis.set_xlabel(r"$\phi$ retenido")
        axis.grid(alpha=0.25)
    axes[0].legend()
    fig.tight_layout()
    fig.savefig(figure_dir / "validacion_cruzada_fgm.pdf")
    plt.close(fig)

    x = np.arange(len(PHI_VALUES))
    width = 0.36
    fig, axis = plt.subplots(figsize=(6.5, 3.8))
    axis.bar(
        x - width / 2,
        continuation["bounded"]["solve_time_s"],
        width,
        color="#155c8a",
        label="Acotada (1,15)",
    )
    axis.bar(
        x + width / 2,
        continuation["unbounded"]["solve_time_s"],
        width,
        color="#d97706",
        label="No acotada",
    )
    axis.set_xticks(x, [f"{phi:g}" for phi in PHI_VALUES])
    axis.set_xlabel(r"$\phi$")
    axis.set_ylabel("Tiempo de resolución [s]")
    axis.set_yscale("log")
    axis.grid(axis="y", alpha=0.25)
    axis.legend()
    fig.tight_layout()
    fig.savefig(figure_dir / "ablacion_continuacion.pdf")
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--campaign-root",
        type=Path,
        default=Path("FGM/resultados/revision_20260903"),
    )
    parser.add_argument(
        "--figure-dir", type=Path, default=Path("TESIS/figuras")
    )
    args = parser.parse_args()

    root = args.campaign_root.resolve()
    figure_dir = args.figure_dir.resolve()
    profiles = _profile_metrics(root)
    mesh = _mesh_metrics(root)
    table_validation = _table_validation(root)
    continuation = _continuation_ablation(root)
    batch = _batch_comparison(root)
    summary = {
        "campaign_root": str(root),
        "profile_metrics": profiles,
        "mesh_metrics": mesh,
        "table_validation": table_validation,
        "continuation_ablation": continuation,
        "strict_batch_comparison": batch,
    }
    (root / "verification_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )
    _write_csv(
        root / "profile_metrics.csv",
        profiles,
        [
            "phi",
            "Su_v2",
            "Su_cantera",
            "Su_error_percent",
            "nodes_v2",
            "nodes_cantera",
            "width_v2_m",
            "width_cantera_m",
            "mass_flow_error_v2",
            "mass_flow_error_cantera",
            "mass_fraction_sum_error_v2",
            "mass_fraction_sum_error_cantera",
            "temperature_l2_dynamic",
            "temperature_linf_K",
            "qdot_l2_relative",
            "qdot_linf_relative",
        ],
    )
    _write_csv(
        root / "mesh_metrics.csv",
        mesh,
        [
            "solver",
            "level",
            "nodes",
            "width_m",
            "Su_m_per_s",
            "Su_change_to_ultra_percent",
            "solve_time_s",
        ],
    )
    _make_figures(root, figure_dir, profiles, mesh, table_validation, continuation)
    print(root / "verification_summary.json")
    print(figure_dir)


if __name__ == "__main__":
    main()
