# -*- coding: utf-8 -*-
"""
plot_saved_comparison.py

Loads data generated by run_saved_comparison.py and writes clean plots:
- Temperature vs length
- Velocity vs length
- Product mass fractions vs length
- Flame speed comparison
"""
from __future__ import annotations

import argparse
from pathlib import Path
import numpy as np


def _load_npz(run_dir: Path) -> dict[str, np.ndarray]:
    npz_path = run_dir / "comparison_data.npz"
    if not npz_path.exists():
        raise FileNotFoundError(f"Missing file: {npz_path}")
    with np.load(npz_path, allow_pickle=False) as data:
        return {k: data[k] for k in data.files}


def _latest_run_dir(output_root: Path) -> Path:
    if not output_root.exists():
        raise FileNotFoundError(f"Missing output root: {output_root}")
    runs = [p for p in output_root.iterdir() if p.is_dir() and p.name.startswith("run_")]
    if not runs:
        raise FileNotFoundError(f"No run_* folders found in {output_root}")
    runs.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return runs[0]


def _select_products(
    species_names: list[str],
    Y_cantera: np.ndarray,
    Y_ours_on_ct: np.ndarray | None,
    max_products: int,
) -> list[int]:
    if Y_cantera.size == 0:
        return []

    delta_ct = Y_cantera[:, -1] - Y_cantera[:, 0]
    if Y_ours_on_ct is not None and Y_ours_on_ct.size:
        delta_ours = Y_ours_on_ct[:, -1] - Y_ours_on_ct[:, 0]
        score = np.maximum(delta_ct, delta_ours)
    else:
        score = delta_ct

    idx_sorted = np.argsort(score)[::-1]
    selected = [int(i) for i in idx_sorted if score[i] > 1e-6]
    if not selected:
        outlet = Y_cantera[:, -1]
        if Y_ours_on_ct is not None and Y_ours_on_ct.size:
            outlet = np.maximum(outlet, Y_ours_on_ct[:, -1])
        idx_sorted = np.argsort(outlet)[::-1]
        selected = [int(i) for i in idx_sorted[:max_products]]

    selected = selected[: max(1, int(max_products))]
    selected = [i for i in selected if 0 <= i < len(species_names)]
    return selected


def _interp_species(z_src: np.ndarray, Y_src: np.ndarray, z_dst: np.ndarray) -> np.ndarray:
    out = np.empty((Y_src.shape[0], z_dst.size), dtype=float)
    for k in range(Y_src.shape[0]):
        out[k, :] = np.interp(z_dst, z_src, Y_src[k, :])
    return out


def generate_clean_plots(
    run_dir: str | Path,
    max_products: int = 6,
    align_domains: bool = True,
) -> list[Path]:
    run_dir = Path(run_dir)
    data = _load_npz(run_dir)

    species_names = [str(s) for s in data["species_names"].tolist()]
    z_ct = np.asarray(data["z_cantera"], dtype=float)
    u_ct = np.asarray(data["u_cantera"], dtype=float)
    T_ct = np.asarray(data["T_cantera"], dtype=float)
    Y_ct = np.asarray(data["Y_cantera"], dtype=float)

    has_ours = bool(int(np.asarray(data["has_ours"]).ravel()[0]))
    z_ours = np.asarray(data["z_ours"], dtype=float)
    u_ours = np.asarray(data["u_ours"], dtype=float)
    T_ours = np.asarray(data["T_ours"], dtype=float)
    Y_ours = np.asarray(data["Y_ours"], dtype=float)

    Su_ct = float(np.asarray(data["Su_cantera"]).ravel()[0])
    Su_ours = float(np.asarray(data["Su_ours"]).ravel()[0])

    import matplotlib.pyplot as plt

    plt.style.use("seaborn-v0_8-whitegrid")
    plt.rcParams.update(
        {
            "figure.dpi": 140,
            "savefig.dpi": 160,
            "axes.titlesize": 13,
            "axes.labelsize": 11,
            "legend.fontsize": 9,
            "axes.linewidth": 1.0,
            "lines.linewidth": 2.0,
            "font.family": "DejaVu Sans",
        }
    )

    plots_dir = run_dir / "plots"
    plots_dir.mkdir(parents=True, exist_ok=True)
    saved: list[Path] = []

    domain_scaled = False
    title_suffix = ""
    z_ours_plot = z_ours
    u_ours_on_ct = np.asarray(data["u_ours_on_cantera"], dtype=float)
    T_ours_on_ct = np.asarray(data["T_ours_on_cantera"], dtype=float)
    Y_ours_on_ct = np.asarray(data["Y_ours_on_cantera"], dtype=float)

    if has_ours and z_ours.size > 1 and z_ct.size > 1:
        span_ct = float(z_ct[-1] - z_ct[0])
        span_ours = float(z_ours[-1] - z_ours[0])
        if span_ct > 0.0 and span_ours > 0.0:
            scale = span_ct / span_ours
            if align_domains and not np.isclose(scale, 1.0, rtol=0.05, atol=1e-12):
                domain_scaled = True
                z_ours_plot = z_ct[0] + (z_ours - z_ours[0]) * scale
                title_suffix = " (z alineada por ancho de dominio)"
                # Build a consistent comparison on Cantera grid after domain alignment.
                u_ours_on_ct = np.interp(z_ct, z_ours_plot, u_ours)
                T_ours_on_ct = np.interp(z_ct, z_ours_plot, T_ours)
                if Y_ours.ndim == 2 and Y_ours.shape[1] == z_ours.size:
                    Y_ours_on_ct = _interp_species(z_ours_plot, Y_ours, z_ct)

    z_ct_mm = 1e3 * z_ct
    z_ours_mm = 1e3 * z_ours_plot if z_ours_plot.size else z_ours_plot

    fig, ax = plt.subplots(figsize=(8.4, 4.8))
    ax.plot(z_ct_mm, T_ct, color="#1f77b4", label="Cantera")
    if has_ours and z_ours.size:
        ax.plot(z_ours_mm, T_ours, "--", color="#d62728", label="Nuestro")
    ax.set_xlabel("Longitud z [mm]")
    ax.set_ylabel("Temperatura [K]")
    ax.set_title("Temperatura vs longitud" + title_suffix)
    ax.legend(loc="best")
    fig.tight_layout()
    p = plots_dir / "temperature_vs_length.png"
    fig.savefig(p)
    plt.close(fig)
    saved.append(p)

    fig, ax = plt.subplots(figsize=(8.4, 4.8))
    ax.plot(z_ct_mm, u_ct, color="#1f77b4", label="Cantera")
    if has_ours and z_ours.size:
        ax.plot(z_ours_mm, u_ours, "--", color="#d62728", label="Nuestro")
    ax.set_xlabel("Longitud z [mm]")
    ax.set_ylabel("Velocidad u [m/s]")
    ax.set_title("Velocidad axial vs longitud" + title_suffix)
    ax.legend(loc="best")
    fig.tight_layout()
    p = plots_dir / "velocity_vs_length.png"
    fig.savefig(p)
    plt.close(fig)
    saved.append(p)

    product_idx = _select_products(
        species_names=species_names,
        Y_cantera=Y_ct,
        Y_ours_on_ct=(Y_ours_on_ct if has_ours and Y_ours_on_ct.size else None),
        max_products=max_products,
    )
    palette = plt.cm.tab10(np.linspace(0.0, 1.0, max(1, len(product_idx))))
    fig, ax = plt.subplots(figsize=(9.2, 5.4))
    for ii, k in enumerate(product_idx):
        sp = species_names[k]
        color = palette[ii]
        ax.plot(z_ct_mm, Y_ct[k, :], color=color, label=f"{sp} (Cantera)")
        if has_ours and z_ours.size and Y_ours.shape[0] > k:
            ax.plot(
                z_ours_mm,
                Y_ours[k, :],
                "--",
                color=color,
                label=f"{sp} (Nuestro)",
            )
    ax.set_xlabel("Longitud z [mm]")
    ax.set_ylabel("Fraccion masica Y")
    ax.set_title("Productos principales vs longitud" + title_suffix)
    ax.legend(loc="best", ncol=2)
    fig.tight_layout()
    p = plots_dir / "products_vs_length.png"
    fig.savefig(p)
    plt.close(fig)
    saved.append(p)

    labels = ["Cantera"]
    values = [Su_ct]
    colors = ["#1f77b4"]
    if has_ours and np.isfinite(Su_ours):
        labels.append("Nuestro")
        values.append(Su_ours)
        colors.append("#d62728")

    fig, ax = plt.subplots(figsize=(6.2, 4.6))
    bars = ax.bar(labels, values, color=colors, width=0.6)
    for b, val in zip(bars, values):
        ax.text(
            b.get_x() + 0.5 * b.get_width(),
            b.get_height(),
            f"{val:.4f}",
            ha="center",
            va="bottom",
        )
    ax.set_ylabel("Su [m/s]")
    ax.set_title("Comparacion de velocidad de llama")
    fig.tight_layout()
    p = plots_dir / "flame_speed_comparison.png"
    fig.savefig(p)
    plt.close(fig)
    saved.append(p)

    if domain_scaled:
        fig, ax = plt.subplots(figsize=(8.2, 3.8))
        ax.text(
            0.02,
            0.55,
            (
                "Se detectaron dominios distintos:\n"
                f"Cantera = {1e3 * (z_ct[-1] - z_ct[0]):.1f} mm, "
                f"Nuestro = {1e3 * (z_ours[-1] - z_ours[0]):.1f} mm.\n"
                "Las curvas 'Nuestro' se reescalaron en z para comparar frentes."
            ),
            fontsize=10.5,
            va="center",
            ha="left",
            transform=ax.transAxes,
        )
        ax.set_axis_off()
        fig.tight_layout()
        p = plots_dir / "domain_alignment_note.png"
        fig.savefig(p)
        plt.close(fig)
        saved.append(p)

    if has_ours and z_ct.size and u_ours_on_ct.size and T_ours_on_ct.size:
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8.6, 6.0), sharex=True)
        ax1.plot(z_ct_mm, T_ours_on_ct - T_ct, color="#2ca02c")
        ax1.axhline(0.0, color="black", lw=1.0, alpha=0.6)
        ax1.set_ylabel("Delta T [K]")
        ax1.set_title("Diferencia Nuestro - Cantera en malla de Cantera")

        ax2.plot(z_ct_mm, u_ours_on_ct - u_ct, color="#9467bd")
        ax2.axhline(0.0, color="black", lw=1.0, alpha=0.6)
        ax2.set_ylabel("Delta u [m/s]")
        ax2.set_xlabel("Longitud z [mm]")
        fig.tight_layout()
        p = plots_dir / "difference_profiles_on_cantera_grid.png"
        fig.savefig(p)
        plt.close(fig)
        saved.append(p)

    return saved


def main():
    # Generated output belongs to the user's working directory, never site-packages.
    script_dir = Path('runs')

    parser = argparse.ArgumentParser(
        description="Generate comparison plots from a saved run.",
        epilog=(
            "Ejemplos de uso:\n"
            "  python -m kava.reference.plot                          # usa la corrida mas reciente\n"
            "  python -m kava.reference.plot runs/comparisons/run_20260425_151755\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "run_dir",
        nargs="?",
        default=None,
        help="Path to run_<timestamp> folder. If omitted, latest run is used.",
    )
    parser.add_argument(
        "--output-root",
        type=str,
        default=None,
        help="Root folder with run_* dirs. Default: runs/comparisons.",
    )
    parser.add_argument(
        "--max-products",
        type=int,
        default=6,
        help="Max number of product species to plot.",
    )
    parser.add_argument(
        "--no-align-domains",
        action="store_true",
        help="Do not rescale z when Cantera and our domain widths differ.",
    )
    args = parser.parse_args()

    if args.run_dir is not None:
        # User gave an explicit path
        run_dir = Path(args.run_dir)
        if not run_dir.is_absolute():
            # Try relative to CWD first, then relative to script dir
            if not run_dir.exists():
                run_dir = script_dir / args.run_dir
    else:
        # Auto-detect latest run
        if args.output_root is not None:
            output_root = Path(args.output_root)
        else:
            output_root = script_dir / "comparisons"
        run_dir = _latest_run_dir(output_root)

    if not run_dir.exists():
        print(f"ERROR: Run folder not found: {run_dir}")
        print(f"\nAvailable runs in {script_dir / 'comparisons'}:")
        cr = script_dir / "comparisons"
        if cr.exists():
            for p in sorted(cr.iterdir()):
                if p.is_dir() and p.name.startswith("run_"):
                    print(f"  {p.name}")
        else:
            print("  (comparison_runs folder does not exist)")
        raise SystemExit(1)

    plot_paths = generate_clean_plots(
        run_dir,
        max_products=int(args.max_products),
        align_domains=not bool(args.no_align_domains),
    )
    print(f"Run folder: {run_dir.resolve()}")
    print("Plots created:")
    for p in plot_paths:
        print(f"  - {p.resolve()}")


if __name__ == "__main__":
    main()
